### ISSUE TITLE
Writing 500 error HTTP response on uncaught errors 

### ISSUE THREAD

**Issue by Guseyn** [tapjs/async-hook-domain#14]
I'm not sure whether this library covers the use case that's been described [here](https://nodejs.org/api/domain.html#warning-dont-ignore-errors).
So, basically if I want to send 500 response to a specific user if something bad happened to its request, I need to use Cluster API with Domains (which works fine and I like generally how API looks, and to be honest I don't see how I can do it differently). I am just a bit concerned about deprecation status for Domains.

So, I am just curious how I can do the same using this lib. I don't see how I can add `request` and `response` to Domain, like for example:

```js
const d = domain.create()
d.add(req);
d.add(res);
```

**Comment by isaacs** [comment]
You don't have to manually add the req and res, just initiating the domain is enough.  Any async behaviors started after the domain creation are included in that domain, and any domains created within async behaviors in that domain are children of that domain.

Here's a little example server:

```js
const {createServer} = require('http')
const Domain = require('./')

const maybeThrow = () => {
  if (Math.random() < 0.5) {
    throw new Error('failed the coin flip')
  }
}

const server = createServer((req, res) => {
  const d = new Domain(er => {
    console.error('domain caught error', er)
    res.statusCode = 500
    res.end('failed in some way: ' + er.stack + '\n')
  })

  console.log(`${req.method} ${req.url}`)
  res.setHeader('connection', 'close')
  res.on('finish', () => d.destroy())
  setTimeout(() => {
    maybeThrow()
    res.statusCode = 200
    res.end('this is fine\n')
  })
})
server.listen(3000, () => console.log('listening on http://localhost:3000'))
```

**Comment by isaacs** [comment]
You should still not just send a 500 and be done with it, though, for all the reasons the linked node doc says.  Better to call `server.close()` to stop accepting connections, terminate gracefully (or ungracefully after some period of time), and let the whatever cluster parent process or OS supervisor or load balancer spin up a new fresh instance.

**Comment by Guseyn** [comment]
@isaacs Thanks for the example, I will definitely try it.
Sure, I have load balancer which handles failed subprocesses, and gracefully restarts them if needed.
I will try to test this library instead of default domain module in Node.
Thanks again for the reply.
